borderzero/border0-go

- README.md
- go.mod
- go.sum
- lib/types/pointer/README.md
- lib/types/pointer/pointer.go
- lib/types/pointer/pointer_test.go
- lib/types/set/README.md
- lib/types/set/set.go
- lib/types/slice/README.md
- lib/types/slice/slice.go
Initial README and libs { set, slice, pointer }
> Initial README and libs { set, slice, pointer }

- service/connector/types/README.md
- service/connector/types/plugin.go
Unified model for connector plugins.
Note that this is far from being the final state of this. It's only a start and everything may change! This repo is not fit for public consumption yet.
[ME-1606]: https://mysocket.atlassian.net/browse/ME-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1606] Connector Plugin Configuration Model

- README.md
- lib/types/slice/slice.go
Modify Map function in slice package
> Modify Map function in slice package

- LICENSE
Populate Apache License Template
> Apache License Template

- service/connector/types/plugin.go
[ME-1626]: https://mysocket.atlassian.net/browse/ME-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1626] change plugin configuration scan interval to minutes

- service/connector/types/upstream_config.go
- adding the connector socket upstream configuration that includes types needed to pass through connector
> [ME-1644] adding the upstream configuration for connector

- lib/types/maps/maps.go
- service/connector/types/plugin.go
[ME-1667]: https://mysocket.atlassian.net/browse/ME-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1667] Completed Kubernetes Discovery Plugin Config

- service/connector/types/plugin.go
- Adds filtering opts for docker containers based on container labels
[ME-1673]: https://mysocket.atlassian.net/browse/ME-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1673] Add Docker Discovery Filtering Options (by Label)

- service/connector/types/upstream_config.go
- adding more information to the upstream configuration
> [ME-1666] adding more information for aws ssm and ec2 connect

- service/connector/types/plugin.go
[ME-1684]: https://mysocket.atlassian.net/browse/ME-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1684] Remove Unused SSM Plugin Type

- service/connector/types/upstream_config.go
Summary
- that will be used to connect with private key method
> Add the username inside the ssh private key details

- service/connector/types/metadata.go
[ME-1739]: https://mysocket.atlassian.net/browse/ME-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1739] Add omitempty tags, fix typo

- service/connector/types/upstream_config.go
Fixes:
- https://mysocket.atlassian.net/browse/ME-1801
[ME-1801]: https://mysocket.atlassian.net/browse/ME-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1801] Built In SSH Server Options

- client/connector.go
- client/connector_test.go
[ME-1821]: https://mysocket.atlassian.net/browse/ME-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1821] Add built-in ssh server support to connector object

- service/ssh_service_configuration.go
Need to add more stuff here...
- Need instance id and instance region for ssm (and also prepare it to support ECS targets)
- Need instance id and instance region in ec2 instance connect (was missed before)
- Need to be able to use the username provider options for stuff other than the built-in ssh server
[ME-1866]: https://mysocket.atlassian.net/browse/ME-1866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1866] Final Additions to Upstream Data

- lib/types/null/null.go
- lib/types/regex/regex.go
- types/common/aws.go
- types/connector/plugin.go
- types/service/common.go
- types/service/configuration.go
- types/service/database_service_configuration.go
- types/service/http_service_configuration.go
- types/service/ssh_service_configuration.go
- types/service/tls_service_configuration.go
Validation for the service configuration object.
Currently only SSH is completed -- to keep the PR small.
[ME-1868]: https://mysocket.atlassian.net/browse/ME-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1868] SSH Service Configuration Validation

- lib/types/netaddr/ipv4.go
- types/service/common.go
- types/service/ssh_service_configuration.go
- types/service/tls_service_configuration.go
Validation for the TLS service upstream configuration.
[ME-1868]: https://mysocket.atlassian.net/browse/ME-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1868] TLS Upstream Config Validation

- types/service/http_service_configuration.go
[ME-1868]: https://mysocket.atlassian.net/browse/ME-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1868] Http Upstream Config Validation

- lib/types/null/null.go
- lib/types/null/null_test.go
- types/service/configuration_test.go
Next change we'll make this `Any`.
> [MISC] Unit Tests for "null" library

- lib/types/set/concurrencysafe.go
- lib/types/set/set.go
- lib/types/set/simple.go
> [MISC] Add Concurrency Safe Set Implementation

- lib/types/set/concurrencysafe.go
- lib/types/set/concurrencysafe_test.go
- lib/types/set/set.go
- lib/types/set/simple.go
- lib/types/set/simple_test.go
[ME-1886]: https://mysocket.atlassian.net/browse/ME-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1886] Unit Tests for Set Types

- types/service/common_test.go
- types/service/http_service_configuration.go
- types/service/http_service_configuration_test.go
- types/service/tls_service_configuration.go
- types/service/tls_service_configuration_test.go
Part of https://mysocket.atlassian.net/browse/ME-1886
[ME-1886]: https://mysocket.atlassian.net/browse/ME-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1886] Unit Tests for HTTP and TLS Service Configuration

- types/common/aws.go
- types/common/aws_test.go
- types/service/http_service_configuration_test.go
- types/service/ssh_service_configuration.go
- types/service/ssh_service_configuration_test.go
Unit tests and a couple of bug fixes found during testing.
Part of https://mysocket.atlassian.net/browse/ME-1886
[ME-1886]: https://mysocket.atlassian.net/browse/ME-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-1886] Unit Tests: ssh service configuration (part 2/2)

- lib/types/wildcard/wildcard.go
- lib/types/wildcard/wildcard_test.go
Need this somewhere :p -- was part of the api, now being moved here.
[ME-2044]: https://mysocket.atlassian.net/browse/ME-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2044] Add Wildcard Matching Library

- types/service/ssh_service_configuration.go
Still very much subject to change -- until then k8s remains behind the "experimental" feature ff. I would like input from @btoonk  on how best to filter these things. But for now, this allows the code to go in fully featured.
- https://mysocket.atlassian.net/browse/ME-2352
[ME-2352]: https://mysocket.atlassian.net/browse/ME-2352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2352] Revised Schema for K8s

- client/policy.go
- client/policy_test.go
[ME-2537]: https://mysocket.atlassian.net/browse/ME-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2537] Add Group Section to Policy Document Body

- .github/workflows/run_tests.yml
- go.mod
- go.sum
- types/service/configuration.go
- types/service/tcp_service_configuration.go
- types/service/tcp_service_configuration_test.go
[ME-2652]: https://mysocket.atlassian.net/browse/ME-2652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2652] Introduce TCP Sockets (deprecating TLS)

- types/service/configuration.go
- types/service/configuration_test.go
[ME-2652]: https://mysocket.atlassian.net/browse/ME-2652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2652] Patch Bug In TLS

- lib/types/nilcheck/nil_check.go
- types/service/configuration.go
- types/service/configuration_test.go
- types/service/ssh_service_configuration.go
- types/service/ssh_service_configuration_test.go
[ME-2671]: https://mysocket.atlassian.net/browse/ME-2671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2671] Simplify Validator Logic

- types/service/vnc_service_configuration.go
- types/service/vnc_service_configuration_test.go
[ME-2704]: https://mysocket.atlassian.net/browse/ME-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2704] Add Password to VNC Upstream Config

- types/service/ssh_service_configuration.go
New ssh based upstream type `docker_exec` to leverage a connector's access to the Docker daemon e.g. via `/var/run/docker.sock` to get shells in sockets.
[ME-2794]: https://mysocket.atlassian.net/browse/ME-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2794] Docker Exec Upstream Configuration

- types/service/ssh_service_configuration.go
- types/service/ssh_service_configuration_test.go
Container name allowlist for docker exec upstream :) 
[ME-2794]: https://mysocket.atlassian.net/browse/ME-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-2794] Container Name Allowlist for Docker Exec

- client/policy.go
- lib/osutil/homedir.go
- lib/types/empty/empty.go
- lib/types/maps/maps.go
- types/service/configuration.go
- types/service/kubernetes_service_configuration.go
- types/service/kubernetes_service_configuration_test.go
[ME-3065]: https://mysocket.atlassian.net/browse/ME-3065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ME-3074]: https://mysocket.atlassian.net/browse/ME-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3065] Adds Kubernetes Socket + Policy Configuration

- types/recordings/recordings.go
[ME-3172]: https://mysocket.atlassian.net/browse/ME-3172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3172] Add Recording Type Constants

- lib/nacl/nacl.go
[ME-3440]: https://mysocket.atlassian.net/browse/ME-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3440] NaCl Box Challenge Library

- lib/nacl/challenge.go
- lib/nacl/key.go
- lib/nacl/nacl.go
- lib/nacl/nonce.go
- Improved package organization
- Improved key abstractions
[ME-3440]: https://mysocket.atlassian.net/browse/ME-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3440] Improved NaCl Library with Utility Funcs

- lib/nacl/key.go
[ME-3440]: https://mysocket.atlassian.net/browse/ME-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3440] Add Base64 Utility Functions to NaCl Keys Lib

- go.mod
- go.sum
- lib/types/ring/ring.go
Need this in the new super secret project -- for calculating a running average of network RTTs.
[ME-3486]: https://mysocket.atlassian.net/browse/ME-3486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3486] Add Simple Ring Buffer Implementation

- types/service/configuration.go
- types/service/configuration_test.go
- types/service/subnet_router_service_configuration.go
- types/service/subnet_router_service_configuration_test.go
[ME-3512]: https://mysocket.atlassian.net/browse/ME-3512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3512] Subnet Router Socket Configuration

- types/service/configuration.go
- types/service/configuration_test.go
- types/service/subnet_routes_service_configuration.go
- types/service/subnet_routes_service_configuration_test.go
[ME-3512]: https://mysocket.atlassian.net/browse/ME-3512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-3512] Rename "Subnet Router" to "Subnet Routes"

- lib/types/ring/ring.go
- lib/types/ring/ring_test.go
[ME-4181]: https://mysocket.atlassian.net/browse/ME-4181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-4181] Add Percentile Functionality to Ring + Tests

- lib/vpnutil/qos/qos.go
[ME-4210]: https://mysocket.atlassian.net/browse/ME-4210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-4210] Add QOS Support to Client Portal

- types/service/database_service_configuration.go
- database name is best naming standard
> Change DatabaseNameOverride to DatabaseName

- go.mod
- go.sum
- lib/uuip/uuip.go
- lib/uuip/uuip_test.go
[ME-4981]: https://mysocket.atlassian.net/browse/ME-4981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-4981] Add UUIP Library

- client/group.go
- client/group_test.go
- client/pagination.go
- listen/mocks/api_client_requester.go
[ME-5075]: https://mysocket.atlassian.net/browse/ME-5075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ME-5075] Introduce Paginators (groups for now)
