go.mod

Go module was initialized in a fork -- and so the path got borked. This sets things right.

Fix go module declared path

---

lib/types/pointer/README.md
lib/types/set/README.md
lib/types/slice/README.md
lib/types/slice/slice.go
service/connector/types/README.md

- Go reportcard links now point to the top level module URL
- Adds the Map function to the slice package

Add Map function to slice package, fix goreportcard

---

service/connector/types/plugin.go

Add the `"omitempty"` directive to the json tag of regions in aws related connector plugin configuration.

Make AWS Regions Optional in Plugin Config

---

service/connector/types/plugin.go

We've decided we don't want these as part of the configuration object. Perhaps a higher level object -- does not need to be defined now.
[ME-1617]: https://mysocket.atlassian.net/browse/ME-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1617] Remove PluginType and Enabled from Plugin Configuration

---

service/connector/types/plugin.go

[[ME-1667](https://mysocket.atlassian.net/browse/ME-1667)] Remove Statuses Config Opt from K8s Plugin
We decided we will do k8s discovery at the service level -- k8s services don't have a status.
[ME-1667]: https://mysocket.atlassian.net/browse/ME-1667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1667] Remove Statuses Config Opt from K8s Plugin

---

lib/types/maps/maps.go

This is currently implemented as part of border0's discovery library. We are just moving it here so it can be reused more widely.
[ME-1673]: https://mysocket.atlassian.net/browse/ME-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1673] Add MatchesFilters to maps library

---

service/connector/types/plugin.go

We discussed we would not have a standalone SSM discovery plugin; we would have it be an option of the EC2 discovery plugin.
- Part of https://mysocket.atlassian.net/browse/ME-1672
[ME-1672]: https://mysocket.atlassian.net/browse/ME-1672?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1672] Add SSM Status Checks to EC2 Discovery

---

service/connector/types/plugin.go

Accounts for changes to ecs discovery (no longer scanning clusters, scanning services)
- part of https://mysocket.atlassian.net/browse/ME-1679
[ME-1679]: https://mysocket.atlassian.net/browse/ME-1679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1679] Remove cluster status opt from ecs plugin config

---

service/connector/types/plugin.go

- eliminates ssm config (we won't support that as a standalone discoverer)
- modifies network discovery config to have the desired schema
- changes top level network discovery config object json key from `local_network_discovery_plugin_configuration` to `network_discovery_plugin_configuration` -- as its more accurate.
[ME-1684]: https://mysocket.atlassian.net/browse/ME-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1684] Network Discovery Plugin Config

---

service/connector/types/metadata.go
service/connector/types/upstream_config.go

- Adds `ConnectorMetadata` with an inner object for ec2 config.
The idea is that this object will be stored in its entirety as JSON. Note that there is no `connector metadata type` field. This is because a connector can have multiple types of metadata.
- Removes unused aws availability zone and duplicate AWS profile object in AWSConfiguration (used aws profile is inside aws credentials object).
[ME-1739]: https://mysocket.atlassian.net/browse/ME-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1739] Add connector metadata types

---

lib/types/slice/slice.go

A small function to count the elements in a slice that satisfy a condition.
---
Usage in the API's connector serializer:
```
// SerializeConnector returns a connector in its serialized form
func SerializeConnector(c models.Connector) Connector {
connector := Connector{
// ...
ActivePlugins: CountWhere(c.ConnectorPlugins, pluginEnabled),
// ...
}
return connector
}
func pluginEnabled(plugin models.ConnectorPlugin) bool {
return pointer.ValueOrZero(plugin.Enabled)
}
```

/lib: Add CountWhere slice fn

---

service/connector/types/upstream_config.go

Including the border0 certificate options
- currently, we will only use a username as optional

[ME-1738] include border0 certificate details

---

service/connector/types/upstream_config.go

What's on the tin^
[ME-1801]: https://mysocket.atlassian.net/browse/ME-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1801] Add upstream connection type for built in ssh

---

service/common.go
service/connector/types/upstream_config.go
service/database_service_configuration.go
service/http_service_configuration.go
service/service_configuration.go
service/ssh_service_configuration.go
service/tls_service_configuration.go

I propose mutually exclusive configuration whenever there are multiple possible types of something and only one of them can exist at a given time.
Note to reviewers:
- start off of `service/service_configuration.go`
- check out `service/ssh_configuration.go` next
- note that every object has its own validator...

Upstream Configuration Wishlist

---

listen/listener.go
listen/listener_test.go
listen/option.go

This is a patch to no-op behaviour from `ensurePoliciesAttached` method.
If `WithPolicies` option is NOT used and `policyNames` remains nil, no-op from listener's `ensurePoliciesAttached` method. If `WithPolicies` option is configured with an empty slice, all policies will be detached from listener's socket.

ME-1847: make listener's `policyNames` fields optional

---

types/service/http_service_configuration.go
types/service/tls_service_configuration.go

Adds service configuration for the remaining 3 connector-managed socket types e.g.
- The built-in http file server (http socket)
- The vpn (tls socket)
- The http proxy (tls socket)
Fixes:
- part of https://mysocket.atlassian.net/browse/ME-1822
- part of https://mysocket.atlassian.net/browse/ME-1823
- part of https://mysocket.atlassian.net/browse/ME-1824
[ME-1822]: https://mysocket.atlassian.net/browse/ME-1822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ME-1823]: https://mysocket.atlassian.net/browse/ME-1823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ME-1824]: https://mysocket.atlassian.net/browse/ME-1824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …

[ME-1822,ME-1823,ME-1824] Service Config for Connector Managed Sockets

---

types/service/http_service_configuration.go

- adding host /sni header to the http standard services

adding host sni header to standard http sockets

---

types/service/ssh_service_configuration.go
types/service/ssh_service_configuration_test.go

Part 1 of 2 parts for ssh service upstream config validator unit tests
Part of https://mysocket.atlassian.net/browse/ME-1886
[ME-1886]: https://mysocket.atlassian.net/browse/ME-1886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-1886] Unit Tests: ssh service configuration (part 1/2)

---

client/socket_test.go
types/service/configuration.go
types/service/configuration_test.go

add a new config for connector socket that includes socket config like connector auth flag, and upstream configs for ssh, database, http and tls. this new top level connector socket config will be sent between api and connectors through grpc, it will replace the existing upstream config.

ME-1893: new service config for connector socket

---

client/connector.go

Embed and return connector's built-in ssh service (socket) from connector's CRUD methods

ME-1960: return connector built-in ssh service

---

types/service/ssh_service_configuration.go
types/service/ssh_service_configuration_test.go

We've decided that allowing prompting of username when the ssh mechanism is username + password OR username + private key is not desirable and only adds confusion to the product.

[ME-2244] Remove Username Provider Opts from Standard SSH Methods

---

client/socket.go
types/service/ssh_service_configuration.go

Also deprecated a NO-OP field in the socket config.
[ME-2373]: https://mysocket.atlassian.net/browse/ME-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2373] Release Kubectl Exec Sockets

---

types/service/ssh_service_configuration.go

Wrong nil check.
[ME-2373]: https://mysocket.atlassian.net/browse/ME-2373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2373] Fix Bug in AWS EKS Socket Config Validator

---

types/connector/metadata.go

new connector internal metadata includes:
- version
- built date
- ip address
- ip metadata: country, city, region, lat, lon, isp

ME-2417: add connector internal metadata

---

lib/types/maps/maps.go

What's on the tin :) 
When we want to index on both key and value e.g.
```
// DirectoryServiceTypeIDToFriendlyName is a mapping between the service type identifier
// in the database (uint8) and the public friendly name of a directory service type.
DirectoryServiceTypeIDToFriendlyName = map[uint8]string{
DirectoryServiceTypeGenericScim:          "scim_generic",
DirectoryServiceTypeOktaScim:             "scim_okta",
DirectoryServiceTypeMicrosoftEntraIDScim: "scim_microsoft_entra_id",
DirectoryServiceTypeGoogleGroups:         "google_groups",
}
// DirectoryServiceTypeFriendlyNameToID is a mapping between the public friendly name
// of a directory service type and its service type identifier in the database (uint8).
DirectoryServiceTypeFriendlyNameToID = …
```

[ME-2453] Utility to reverse a map

---

.mockery.yaml
client/api_client.go
client/api_client_test.go
client/connector.go
client/connector_test.go
client/mocks/client_http_requester.go
client/policy_test.go
client/socket_test.go
listen/mocks/api_client_requester.go

Adds shorter/faster retries for 404s (where before we wouldn't retry 404s). This is necessary because the Border0 API is replicated across multiple regions and we want to make our SDK more resilient to likely replication lag.
[ME-2633]: https://mysocket.atlassian.net/browse/ME-2633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2633] Add Special Handling of Retries for 404 Responses

---

client/enum/socket_type.go

[ME-2652]: https://mysocket.atlassian.net/browse/ME-2652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2652] Add missing enum for tcp sockets

---

client/enum/socket_type.go
types/service/configuration.go
types/service/vnc_service_configuration.go
types/service/vnc_service_configuration_test.go

Adds upstream service configuration for new vnc type sockets.
[ME-2622]: https://mysocket.atlassian.net/browse/ME-2622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2622] Upstream Service Configuration for VNC Sockets

---

client/enum/socket_type.go
types/service/configuration.go
types/service/rdp_service_configuration.go
types/service/rdp_service_configuration_test.go

Adds upstream service configuration for new rdp type sockets.
[ME-2656]: https://mysocket.atlassian.net/browse/ME-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2656] Upstream Service Configuration for RDP Sockets

---

client/enum/socket_type.go
types/service/configuration.go
types/service/vpn_service_configuration.go
types/service/vpn_service_configuration_test.go

Adds upstream service configuration for new vpn type sockets.
[ME-2657]: https://mysocket.atlassian.net/browse/ME-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2657] Upstream Service Configuration for VPN Sockets

---

lib/types/set/concurrencysafe.go
lib/types/set/concurrencysafe_test.go
lib/types/set/set.go
lib/types/set/simple.go
lib/types/set/simple_test.go

Need our set types to have an equality method... need it for a change in the API.
[ME-2608]: https://mysocket.atlassian.net/browse/ME-2608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2608] Add method Equals(Set[T]) to set type

---

types/service/vpn_service_configuration.go
types/service/vpn_service_configuration_test.go

Had a long chat with chatGPT to come up with more explicit/straightforward field names.
`VpnSubnet` --> `DHCPPoolSubnetV4`
`Routes`  --> `AdvertisedRoutesV4`
[ME-2657]: https://mysocket.atlassian.net/browse/ME-2657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2657] Improve VPN Socket Upstream Config Field Names

---

client/socket.go

[ME-2810]: https://mysocket.atlassian.net/browse/ME-2810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2810] Add DNS Name as Socket Output Field

---

go.mod

See https://github.com/srl-labs/containerlab/pull/1990 (specifically https://github.com/srl-labs/containerlab/pull/1990#discussion_r1563978247) -- in this case containerlab would have to upgrade their version of go in order to use *this* package.
It is a good idea to use `goN-1` version for broader adoption and allow SDK users to upgrade their version of Go before we do here. 
[ME-2810]: https://mysocket.atlassian.net/browse/ME-2810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-2810] Downgrade Go to Latest-1 (1.21)

---

lib/nacl/challenge.go

Little bug sneaked in last commit.
[ME-3440]: https://mysocket.atlassian.net/browse/ME-3440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ME-3440] Fix Key Type Bug in NaCl Lib
